<?php

namespace AppBundle\Repository;

/**
 * CorredorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorredorRepository extends \Doctrine\ORM\EntityRepository
{
}
