<?php

namespace AppBundle\Repository;

/**
 * DistanciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistanciaRepository extends \Doctrine\ORM\EntityRepository
{
}
