<?php

namespace AppBundle\Repository;

/**
 * TalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalleRepository extends \Doctrine\ORM\EntityRepository
{
}
