<?php

namespace AppBundle\Repository;

/**
 * TipoCarreraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCarreraRepository extends \Doctrine\ORM\EntityRepository
{
}
